// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = SECRET_OPTIONAL_LOGIN;

const char SSID[] = SECRET_SSID;             // Network SSID (name)
const char PASS[] = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[] = SECRET_DEVICE_KEY; // Secret device password

void onUiMessengerChange();
void onUiMovementChange();
void onTemperatureChange();
void onMoveBChange();
void onMoveFChange();
void onMoveLChange();
void onMoveRChange();

String ui_messenger;
String ui_movement;
float temperature;
bool move_B;
bool move_F;
bool move_L;
bool move_R;

void initProperties()
{

    ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
    ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
    ArduinoCloud.addProperty(ui_messenger, READWRITE, ON_CHANGE, onUiMessengerChange);
    ArduinoCloud.addProperty(ui_movement, READWRITE, ON_CHANGE, onUiMovementChange);
    ArduinoCloud.addProperty(temperature, READWRITE, ON_CHANGE, onTemperatureChange);
    ArduinoCloud.addProperty(move_B, READWRITE, ON_CHANGE, onMoveBChange);
    ArduinoCloud.addProperty(move_F, READWRITE, ON_CHANGE, onMoveFChange);
    ArduinoCloud.addProperty(move_L, READWRITE, ON_CHANGE, onMoveLChange);
    ArduinoCloud.addProperty(move_R, READWRITE, ON_CHANGE, onMoveRChange);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
